language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - composer require satooshi/php-coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:

after_success:
  - php vendor/bin/coveralls -v;
