language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v;
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="xjSPxZCm8blcF0PE0gx82AO0JVONtgJ2f" --format=php-clover build/logs/clover.xml